pipeline {
    agent any 
    stages {
        stage ('Clean workspace') {
        steps {
            cleanWs()
            }
        }
        stage ('Git Checkout') {
        steps {
            git branch: 'master', credentialsId: 'imad', url: 'https://github.com/NotEvenAiming/TarkovApi'
            }
        }
        stage('Restore packages') {
        steps {
            sh "dotnet restore ${workspace}/EindProjectCloudApi/EindProjectCloudApi.sln"
             }
        }
            stage('Build') {
        steps {
            sh "dotnet build ${workspace}/EindProjectCloudApi/EindProjectCloudApi.sln"
        }
    }

   }
    post {
        always {
            emailext body: 'The build is succesfull', recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']], subject: 'Jenkins build'
        }
    }
}
