
pipeline {
    agent any 
    stages {
        stage ('Clean workspace') {
        steps {
            cleanWs()
            }
        }
        stage ('Git Checkout') {
        steps {
            git branch: 'master', credentialsId: 'imad', url: 'https://github.com/NotEvenAiming/TarkovApi'
            }
        }
        stage('Restore packages') {
        steps {
            sh "dotnet restore ${workspace}/EindProjectCloudApi/EindProjectCloudApi.sln"
             }
        }
        stage('Build') {
        steps {
            sh "msbuild.exe ${workspace}\\EindProjectCloudApi\\EindProjectCloudApi.sln /nologo /nr:false  /p:platform=\"x64\" /p:configuration=\"release\" /p:PackageCertificateKeyFile=<path-to-certificate-file>.pfx /t:clean;restore;rebuild"
           }
        }
   }
}
